# Generated by Django 4.0.2 on 2022-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name1', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
        ),
    ]
