# Generated by Django 4.0.2 on 2022-03-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place2',
            new_name='Place',
        ),
    ]
