# Generated by Django 4.0.2 on 2022-03-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_place2_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name1',
        ),
    ]
